### ISSUE TITLE
AutoHeight prop causes warning: Mutating `style` is deprecated

### ISSUE THREAD

**Issue by Niryo** [malte-wessel/react-custom-scrollbars#104]
Im trying to use the scrollbar with autoHeight but it triggers the following warning:

> Warning: `div` was passed a style object that has previously been mutated. Mutating `style` is deprecated. Consider cloning it beforehand. Check the `render` of `Scrollbars`. Previous style: {position: "relative", top: undefined, left: undefined, right: undefined, bottom: undefined, overflow: "scroll", WebkitOverflowScrolling: "touch", marginRight: 0, marginBottom: 0, minHeight: NaN, maxHeight: NaN}. Mutated style: {position: "relative", top: undefined, left: undefined, right: undefined, bottom: undefined, overflow: "scroll", WebkitOverflowScrolling: "touch", marginRight: 0, marginBottom: 0, minHeight: NaN, maxHeight: NaN}.

This is how I am using the Scrollbar:
```
    const scrollAreaProps = {
      autoHeightMax: 246,
      autoHeightMin: 116,
      autoHeight: true
    };

      <Scrollbars ref={this.saveScrollbarRef} {...scrollAreaProps}>
              <ul>
                {this.generateList()}
              </ul>
       </Scrollbars>
```
  

Am I missing something?
Thanks!

**Comment by ash-developer** [comment]
i used your scrollAreaProps into my project and everything was good
can you show your package.json and full code of component where you are using scrollbar?

**Comment by ash-developer** [comment]
found the issue
as i understand Nirio is working with repo https://github.com/Niryo/react-playground
there he is using jsdom for tests and that lib doesn't provide properties offsetWidth and clientWidth for elements
current repo has util function getScrollbarWidth which uses these properties
and the result is NaN because undefined - undefined = NaN
scrollbar uses that result for generate styles and react throw warning for mutate NaN

to prevent such situation:
```
function getScrollbarWidth() {
    ...

    return scrollbarWidth || 0;

}
```

**Comment by Niryo** [comment]
@ash-developer Great job man:) BTW Im sorry I wasn't responsive in providing the exact project details...Im glad you figured it out anyway
