### ISSUE TITLE
z-index of Bars

### ISSUE THREAD

**Issue by gkhno** [malte-wessel/react-custom-scrollbars#126]
Is there an specific reason that scrollbars don't have any z-index value? I think they should have high z-index values to ensure they are visible.

**Comment by malte-wessel** [comment]
You can customize every element to your needs. See: https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/customization.md

**Comment by chuanqisun** [comment]
Hi Malte, first of all I really love this library. Thanks for the amazing work.

Regarding to ghkno's question, I wonder if there is a way to customize the thumb style _on top of the_ out-of-the-box element. I understand each element is fully customizable because we have full control over the render function. On the other hand, you've already done an amazing job giving us a great place to start. In most cases, we just need to tweak a little bit from the existing code and rewriting the entire render function and handling the scroll position manually seems to be an overkill.

Would you be open to allowing customizers to inject styles or classNames onto the existing thumb element?
