### ISSUE TITLE
React 15.5.0 deprecation error

### ISSUE THREAD

**Issue by lookapanda** [malte-wessel/react-custom-scrollbars#141]
> Warning: Scrollbars: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by MichaelDeBoey** [comment]
`React.createClass` has been deprecated to since [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings).

The following warning is displayed if that version of React is used:
`Warning: DocumentTitle: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

CC: @malte-wessel
