### ISSUE TITLE
This library does not work at all

### ISSUE THREAD

**Issue by pavle-lekic-htec** [malte-wessel/react-custom-scrollbars#199]
All I see is the default Chrome/Firefox/Safari scrollbars, nothing is custom. I wasted around 4 hours trying to style the bars/handles and didn't succeed at all. I also saw other people commenting here that the library didn't work for them too. I even tried earlier version 3.1, and nothing again. So, sorry to say this, but this library is total crap and I hope that other people see this so they don't waste their whole day trying to fix this junk.

**Comment by malte-wessel** [comment]
Well, apparently this library [works](https://codepen.io/drbreak/pen/KVEMyd?editors=0010) for a lot of people. Maybe you could explain your issue a bit more detailed so that other people can help you.

Also, remember this is open source software, people are spending their free time to work on the code so others can use it. So, the next time you are about to go nuts, use your brain, find a fix and share it.

**Comment by mmtjhlee** [comment]
Recently found out that if you are using a trackpad on OSX, chances are that the library will delegate to the native scroll bar. But once you connect a mouse or config system preference to show a fixed scrollbar it works again -- after reloading. So, I guess this is working as intended.

I was also scratching my head yesterday, that it suddenly stopped showing custom scrollbars. Hope this helps someone googling.
