### ISSUE TITLE
The scrollbars is not rendered properly the first time.

### ISSUE THREAD

**Issue by kossel** [malte-wessel/react-custom-scrollbars#285]
I'm using the scrollbar inside of Gatsby.js.  in development mode it works fine, however when it's bundler for prod, it doesn't render properly.

it adds the overflow to the container but not the -Margin props to hide those native scrollbars, whenever I click any thing, it will work as expected after that, any idea?

you can see it in [this demo side]( https://kossel.github.io)

**Comment by bristoljon** [comment]
This could be down to system settings if on Mac. Chrome respects your system settings on Mac (and possibly other OS's) so the getScrollbarWidth util used by this package returns 0 and no negative margins are added.

**Comment by kossel** [comment]
I tried on every browser (desktop, mobile) still not working.

**Comment by kossel** [comment]
nvm the issue was gatsby related. now it's fixed

**Comment by fabiofcferreira** [comment]
@kossel: Could you please elaborate and let me know what was the issue you faced? I'm having this problem right now and I don't seem to find a good answer.

**Comment by tudi2d** [comment]
I faced the same issue: You have to add the `universal` prop to ensure that the animation runs the same way on the server as it does in your development environment.

**Comment by emailnikola** [comment]
Reopening this exact issue. #285
"gatsby": "^2.19.45",
"react-custom-scrollbars": "^4.2.1",

**Comment by ToanNguyen97** [comment]
Hi! I'm having with this problem too. In develop enviroment, it working but when I build and in my prod enviroment still not working.  
I use:
 "gatsby": "^2.29.2",
"react-custom-scrollbars": "^4.2.1",

**Comment by berke581** [comment]
> I faced the same issue: You have to add the `universal` prop to ensure that the animation runs the same way on the server as it does in your development environment.

This solved my problem too 🚀 .

**Comment by drsounds** [comment]
I have this issue too on our gatsby site we host on Firebase and whats making it even harder is the issue only happens when loading a dynamic route from pages/[...].tsx on our staging firebase hosting but never on gatsby develop or a build after gatsby build...
I tried everything, different browsers, cleared caches, localStorages etc. and nothing improved.
And when comparing the dom elements between the local run and on remote I can see on the correct displaying page it appends a new div with inline styles which is not present on the glitched build, and sometimes this strange behavior fixes when navigating but comes back with a full page reload
