### ISSUE TITLE
Anchor links scroll the inner scrollbar div

### ISSUE THREAD

**Issue by prontiol** [malte-wessel/react-custom-scrollbars#41]
Clicking on anchor links (e.g. `<a href="#link">`) causes a call of `element.scrollIntoView()` on target.
But `scrollIntoView` scrolls to top all ancestors of the target, which have content height greater than element height. So here we have our problem, as we have first wrapper div to have height of 100% and the second inner one to be 100% + 15px (because of negative margins for hiding native scrollbars, number 15 may vary). The first wrapper div scrolls by 15px, moving the content and leaving the gap at the bottom which is unacceptable. Problem appears on Firefox only.
Is there a reason to have native scrollbars visible and hidden by negative margins? Why not just use `overflow: hidden` instead?
Any ideas how to solve the problem I described above?

**Comment by malte-wessel** [comment]
Sorry I don't understand the issue. Could you provide some code or an example?
If we would use `overflow:hidden` we won't get the native scrolling behaviour, which is the core of this library.

**Comment by AluDevelopment** [comment]
https://github.com/malte-wessel/react-custom-scrollbars/issues/41#issue-148316547

Clicking on anchor links (e.g.```<a href="#link"/>```) causes a call of element.scrollIntoView() on target.
But scrollIntoView scrolls to top all ancestors of the target, which have content height greater than element height. So here we have our problem, as we have first wrapper div to have height of 100% and the second inner one to be 100% + 15px (because of negative margins for hiding native scrollbars, number 15 may vary). The first wrapper div scrolls by 15px, moving the content and leaving the gap at the bottom which is unacceptable.

![image](https://user-images.githubusercontent.com/46777570/72122441-e21fc580-3398-11ea-92de-5871b28ce9e7.png)

**Comment by rr-it** [comment]
To resolve unwanted scrolling on anchor-usage use `overflow: clip` instead of `oveflow: hidden`.

See `overflow: hidden` [on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#hidden):
> The content can be scrolled programmatically **[e.g. by anchor]**, in which case the element box is a scroll container.

See `overflow: clip` [on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#clip):
> Overflow content outside the clipped region is not visible, user agents do not add a scroll bar, and programmatic scrolling is also not supported. […] The element box is not a scroll container.
